# yaml-language-server: $schema=https://raw.githubusercontent.com/avil13/vue-act-master/master/packages/act-master-cli/schema/schema.json

config:
  # the path to the folder with the source files relative to this file
  src: './src'
  alias: '@/'
actionsPatterns: # a patterns for finding action files
  - 'utils/__fixtures__/**/*.ts'
generate:
  actionsIndexFile: 'act/act-generate/actions.ts'
  prefixText: '/* This is generated file */'
