name: ActMaster publish npm

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: packages/act-master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
        # Проверяем изменилась ли версия
      - name: Set NEED_PUBLISH
        run: echo "NEED_PUBLISH=$(./need-publish.sh)" >> $GITHUB_ENV

      - run: yarn
        if: ${{ env.NEED_PUBLISH }}

      - run: yarn publish
        if: ${{ env.NEED_PUBLISH }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
